
spring:
  application:
    name: service-discovery
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false


cloud:
  config:
    uri: http://localhost:8888